name = "meamart-directory"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js/index.js"
assets = { directory = "dist/client" }

[dev]
port = 4321

[[kv_namespaces]]
binding = "SESSION"
id = "session-kv-local"

[vars]
ENVIRONMENT = "development"
